[application]

# App (Project) Name
name = "Tix"

# Dioxus App Default Platform
# desktop, web, mobile, ssr
default_platform = "web"

# resource (public) file folder
asset_dir = "public"

[web.app]

# HTML title tag content
title = "Tix"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "public"]

# uncomment line below if using Router
# index_on_404 = true

# include `assets` in web platform
[web.resource]

# CSS style file
style = [
  "tailwind.css",
  "https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;700&display=swap",
]

# Javascript code file
script = []

[web.resource.dev]

# serve: [dev-server] only

# CSS style file
style = []

# Javascript code file
script = []
