# fly.toml app configuration file generated for sthlmvision on 2024-01-08T21:33:34+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sthlmvision"
primary_region = "arn"

[build]

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[http_service.concurrency]
hard_limit = 99999

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 256

[env]
RUST_LOG = "info"
